<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"[]>
<plist version="1.0">
  <!-- Generated via. Iro4CLI -->
  <dict>
    <key>fileTypes</key>
    <array>
      <string>flo</string>
    </array>
    <key>name</key>
    <string>flogram</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#main</string>
      </dict>
    </array>
    <key>scopeName</key>
    <string>source.flogram</string>
    <key>uuid</key>
    <string></string>
    <key>repository</key>
    <dict>
      <key>main</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#numeric</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(\&quot;)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>text.flogram</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>text.flogram</string>
            <key>end</key>
            <string>(\&quot;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>text.flogram</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>(\&apos;)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>text.flogram</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>text.flogram</string>
            <key>end</key>
            <string>(\&apos;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>text.flogram</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>(fn )</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.flogram</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>punctuation.flogram</string>
            <key>end</key>
            <string>(\W|_/g)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.flogram</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>(new )</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.flogram</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>punctuation.flogram</string>
            <key>end</key>
            <string>(\W|_/g)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.flogram</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>(\[A-Za-z]*.)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.flogram</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>keyword.flogram</string>
            <key>end</key>
            <string>(\()|$\)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.flogram</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>(\:\ )</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.flogram</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>punctuation.flogram</string>
            <key>end</key>
            <string>(\W)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.flogram</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>(self )</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.flogram</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>comment.flogram</string>
            <key>end</key>
            <string>([A-Za-z0-9_]*)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>comment.flogram</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(#.*)</string>
            <key>name</key>
            <string>comment.flogram</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(addr_of |any |as |bind |bits |bool |break |contract |else|else |equals |export | get |if |iface |is |import |interface |length |list |loop |member |native |set |types |release |return |value_at |this|this. )</string>
            <key>name</key>
            <string>keyword.flogram</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(true|true |false|false |null|null |zero|zero |None|None |self|self |File|Base)</string>
            <key>name</key>
            <string>punctuation.flogram</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(this|this |break |break)</string>
            <key>name</key>
            <string>text.flogram</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(I8|I8 |I16|I16 |I32|I32 |I64|I64 |U8|U8 |U16|U16 |U32|U32 |U64|U64 |F8|F8 |F16|F16 |F32|F32 |F64|F64 |BOOL|BOOL )</string>
            <key>name</key>
            <string>punctuation.flogram</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\b[A-Z|_][A-Z|_][A-Z0-9_]*)</string>
            <key>name</key>
            <string>punctuation.flogram</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(object )</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.flogram</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>comment.flogram</string>
            <key>end</key>
            <string>(:)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.flogram</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>(-&amp;gt; )</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.flogram</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>comment.flogram</string>
            <key>end</key>
            <string>(:)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.flogram</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>(foreach )</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.flogram</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#helper_Nusf-LM</string>
              </dict>
            </array>
            <key>end</key>
            <string>(:)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.flogram</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>(mut )</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.flogram</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>punctuation.flogram</string>
            <key>end</key>
            <string>( |:)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.flogram</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>(enum )</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.flogram</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>comment.flogram</string>
            <key>end</key>
            <string>( |:)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.flogram</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(:=|:|=|!=)</string>
            <key>name</key>
            <string>punctuation.flogram</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(;)</string>
            <key>name</key>
            <string>invalid.flogram</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([.][A-Za-z0-9_]*)</string>
            <key>name</key>
            <string>punctuation.flogram</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(!|/|%|\(|\)|\[|\])</string>
            <key>name</key>
            <string>punctuation.flogram</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\||\*|-|\+|!|\{|\}|&amp;gt;|\?)</string>
            <key>name</key>
            <string>comment.flogram</string>
          </dict>
        </array>
      </dict>
      <key>numeric</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(\b\d+)</string>
            <key>name</key>
            <string>constant.numeric.flogram</string>
          </dict>
        </array>
      </dict>
      <key>foreach</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#main</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\b[a-z|_][A-Za-z0-9_]*)</string>
            <key>name</key>
            <string>punctuation.flogram</string>
          </dict>
          <dict>
            <key>match</key>
            <string>( in )</string>
            <key>name</key>
            <string>punctuation.flogram</string>
          </dict>
        </array>
      </dict>
      <key>helper_Nusf-LM</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#foreach</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>